{
 "title": "PostgreSQL Table Analyzer",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "schema_name",
    "label": "schena_name",
    "query": "select distinct schema_name from main_stat"
   }
  ]
 },
 "panels": [
  {
   "title": "Read statistic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  created AS \"time\",\n  table_name AS metric,\n  avg(read_val) as \"avg\"\nFROM main_stat\nWHERE\n  $__timeFilter(created) and schema_name = '$schema_name'\ngroup by created,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Update statistic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created,$__interval),\n  table_name AS metric,\n  avg(upd_val) AS \"upd_val\"\nFROM main_stat\nWHERE\n  $__timeFilter(created) and schema_name = '$schema_name'\nGROUP BY created,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Insert statistic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  created AS \"time\",\n  table_name AS metric,\n  avg(ins_val) as \"avg\"\nFROM main_stat\nWHERE\n  $__timeFilter(created) and schema_name = '$schema_name'\n  group by created,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Delete statistic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created,$__interval),\n  table_name AS metric,\n  avg(del_val) AS \"del_val\"\nFROM main_stat\nWHERE\n  $__timeFilter(created) and schema_name = '$schema_name'\nGROUP BY created,2\nORDER BY 1,2"
    }
   ]
  }
 ]
}