server:
  port: ${PORT:2789}

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
  datasource:
    # настройки для базы данных в которую будет писать сам сервис
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:analyzer}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:analyzer}
    user: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    schemas: ${DB_SCHEMA:public}
  # try
  # second-datasource:

# настройки для базы данных, из которой нужно собирать статистику
analyzer:
  datasource:
    url: jdbc:postgresql://${ANALYZER_DB_HOST:localhost}:${ANALYZER_DB_PORT:5432}/${ANALYZER_DB_NAME:analyzer}?currentSchema=pg_catalog
    username: ${ANALYZER_DB_USER:postgres}
    password: ${ANALYZER_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

main-stat-job-cron-expression: "0/1 * * * * ?"

management:
  endpoint:
    metrics:
      enabled: true
