
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
    open-in-view: false
  datasource:
    # настройки для базы данных в которую будет писать сам сервис
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    schemas: ${DB_SCHEMA}
  # try
  # second-datasource:

# настройки для базы данных, из которой нужно собирать статистику
analyzer:
  datasource:
    url: jdbc:postgresql://${ANALYZER_DB_HOST}:${ANALYZER_DB_PORT}/${ANALYZER_DB_NAME}?currentSchema=pg_catalog
    username: ${ANALYZER_DB_USER}
    password: ${ANALYZER_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

main-stat-job-cron-expression: "${MAIN_STAT_CRON_JOB:0 * * * * ?}"
